### ISSUE TITLE
Error installing Raffle and/or Casino on V3

### ISSUE THREAD

**Issue by causefx** [Redjumpman/Jumper-Cogs#153]
**Cog**
- Raffle & Casino
- V3

**Describe the bug**
Trying to install both of these on a v3 instance and get an error.  Not sure if I am doing something wrong.

**To Reproduce**
Install either Raffle or Casino on v3.

**Error Logs**
```
discord-red    | [01/10/2018 21:48] ERROR core_commands _load 98: Package loading failed
discord-red    | Traceback (most recent call last):
discord-red    |   File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 96, in _load
discord-red    |     await bot.load_extension(spec)
discord-red    |   File "/usr/local/lib/python3.6/dist-packages/redbot/core/bot.py", line 230, in load_extension
discord-red    |     lib.setup(self)
discord-red    |   File "/data/cogs/CogManager/cogs/raffle/__init__.py", line 5, in setup
discord-red    |     bot.add_cog(Raffle(bot))
discord-red    |   File "/usr/local/lib/python3.6/dist-packages/redbot/core/bot.py", line 387, in add_cog
discord-red    |     f"The {cog.__class__.__name__} cog in the {cog.__module__} package does "
discord-red    | RuntimeError: The Raffle cog in the raffle.raffle package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16184466/46317936-b143c480-c589-11e8-93b3-9311238b19b6.png)

**Comment by Redjumpman** [comment]
Fixed. I forgot to update to comply with the new standard in Red.

**Comment by causefx** [comment]
Thank you! it works now!
