### ISSUE TITLE
No module named cogs.deck on Casino cog install

### ISSUE THREAD

**Issue by shucktech** [Redjumpman/Jumper-Cogs#162]
Ran the `[p]cog install jumper-cogs casino` and received the following error:
```Copying casino...
[05/12/2018 12:36] ERROR owner load 74: No module named 'cogs.deck'
Traceback (most recent call last):
  File "/home/drt/Red-DiscordBot/cogs/owner.py", line 65, in load
    self._load_cog(module)
  File "/home/drt/Red-DiscordBot/cogs/owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/drt/Red-DiscordBot/cogs/casino.py", line 15, in <module>
    from .deck import Deck
```

**Comment by shucktech** [comment]
Closing the issue, I have v2 installed trying to install v3 of the cog.
