### ISSUE TITLE
Shop Module not loading

### ISSUE THREAD

**Issue by QuiteSmashing** [Redjumpman/Jumper-Cogs#165]
Every since installing the rep and the actual cog for Red, I haven't had any luck running the shop (All of my other cogs run just fine)

The error message I get is:

SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 949, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\jackt\\OneDrive\\Documents\\Red Bot\\Red-DiscordBot\\cogs\\shop.py', 357, 64, '            return await ctx.send(f"You don\'t own any `{item}`.")\n'))
Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 945, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\jackt\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\shop.py", line 357
    return await ctx.send(f"You don't own any `{item}`.")
                                                       ^

I've tried looking through to see what could be causing this, but I have no idea currently.

**Comment by Redjumpman** [comment]
Did you modify the source? because `return await ctx.send(f"You don't own any `{item}`.")\n'))` is not line 357 in the source, and it is very much incorrect.

**Comment by QuiteSmashing** [comment]
Not to my knowledge. I know I installed 3.0 Red before 2.0 (Because it was the first one I was linked to, and didn't know Cogs didn't work on 3.0 just yet). Uninstalled 3.0, Installed 2.0, and got the cogs I wanted to run. I checked the code, looking through with my small amount of knowledge, to see what was wrong but couldn't pinpoint, and closed the file.

I did try uninstalling, reinstalling, or using the repair/factory restart functions to see if that would fix anything. Neither of those worked no matter how many times I tried

**Comment by Redjumpman** [comment]
is this on line 357 of your shop.py file? `return await ctx.send(f"You don't own any `{item}`.")\n'))` ? 
Also can you post what error it gave above this line in the console: `During handling of the above exception, another exception occurred:`

**Comment by QuiteSmashing** [comment]
Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 949, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\jackt\\OneDrive\\Documents\\Red Bot\\Red-DiscordBot\\cogs\\shop.py', 357, 64, '            return await ctx.send(f"You don\'t own any `{item}`.")\n'))
Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 945, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\jackt\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\shop.py", line 357
    return await ctx.send(f"You don't own any `{item}`.")
                                                       ^
SyntaxError: invalid syntax


Here's a pic of my line 357 in notepad++

![line357](https://user-images.githubusercontent.com/47644462/53316198-2a6aed80-3884-11e9-9710-246160cbc5c3.PNG)

**Comment by Redjumpman** [comment]
Hmmm. There wasn't an error above that one? It looks to be the same exception.

**Comment by QuiteSmashing** [comment]
It seems to be repeating the same thing as the last, here's the WHOLE block I get if that helps

I might've copied it wrong when you asked for the above part, that's on me


[24/02/2019 22:32] ERROR owner load 68: ('invalid syntax', ('C:\\Users\\jackt\\OneDrive\\Documents\\Red Bot\\Red-DiscordBot\\cogs\\shop.py', 357, 64, '            return await ctx.send(f"You don\'t own any `{item}`.")\n'))
Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 945, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\jackt\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\shop.py", line 357
    return await ctx.send(f"You don't own any `{item}`.")
                                                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 949, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\jackt\\OneDrive\\Documents\\Red Bot\\Red-DiscordBot\\cogs\\shop.py', 357, 64, '            return await ctx.send(f"You don\'t own any `{item}`.")\n'))
Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 945, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\jackt\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\shop.py", line 357
    return await ctx.send(f"You don't own any `{item}`.")
                                                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\jackt\OneDrive\Documents\Red Bot\Red-DiscordBot\cogs\owner.py", line 949, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\jackt\\OneDrive\\Documents\\Red Bot\\Red-DiscordBot\\cogs\\shop.py', 357, 64, '            return await ctx.send(f"You don\'t own any `{item}`.")\n'))

**Comment by Redjumpman** [comment]
What version of python are you running?

**Comment by QuiteSmashing** [comment]
The version requested to be installed in this website
https://twentysix26.github.io/Red-Docs/red_install_windows/

It's what I could find when I was figuring out how to install Redbot at first

**Comment by Redjumpman** [comment]
Oh god. I miss-read your initial post. You are running a v2 bot... so You can't even use this cog. You would have to use my old, deprecated, un-supported version of shop, which is on a different branch. Red V3 is no longer in beta (not sure when you downloaded it), and there are a ton of cogs that work for V3, although they are not backwards compatible.

**Comment by QuiteSmashing** [comment]
Huh. I was told before that Cogs didn't work in Red 3.0. Good to know, thank you!

**Comment by Redjumpman** [comment]
No worries. If you want to use my old stuff, you need to download from this link: https://github.com/Redjumpman/Jumper-Plugins/tree/V2. But I really really, recommend you use Red V3. You can find a full list of approved repos here: https://cogboard.red/t/approved-repositories/210 . Good luck!
