### ISSUE TITLE
Shop error on shop pending command.

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Redjumpman/Jumper-Cogs#167]
Getting

[21/02/2019 23:57] ERROR events on_command_error 202: Exception in command 'shop pending'
Traceback (most recent call last):
  File "/home/Ian/my_env/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/shop.py", line 326, in pending
    user, item, = await menu.display()
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 21, in display
    item = await self.menu_loop(data, groups, page, maximum, msg)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 71, in menu_loop
    pending_id = await self.pending_menu(data, selection, msg)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 210, in pending_menu
    msg, groups, page, maximum = await self.setup(data=new_data, msg=msg)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 42, in setup
    groups = self.group_data(data)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 163, in group_data
    grouped.append(self.sorter(data[idx:idx + 5]))
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 155, in sorter
    return sorted(groups, key=lambda x: x[1]['Cost'], reverse=True)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/shop/menu.py", line 155, in <lambda>
    return sorted(groups, key=lambda x: x[1]['Cost'], reverse=True)
KeyError: 'Cost'

When using [p]shop pending.

**Comment by Redjumpman** [comment]
I need more information than this. 
What version of shop are you using?
What happened before this error? Was there a specific item that was redeemed to pending before this error occurred?

**Comment by Ianardo-DiCaprio** [comment]
Most up to date version of Shop
I was using the `[p]shop pending` and typing the number next to someones name to view their pending items.
It happens when there are atleast 6 + items in the users pending list
The items were basic items costing 15000 each.
