### ISSUE TITLE
[casino] deleting memberships results in a keyerror

### ISSUE THREAD

**Issue by kennnyshiwa** [Redjumpman/Jumper-Cogs#179]
Was checking out some casino settings i hadn't explored and decided to make a membership to test it out. After making it i then decided to delete it which results in a keyerror, traceback below

command used was ``[p]casino memdesigner`` and then the delete option
```
Traceback (most recent call last):
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kstjohn_kstj_us/.local/share/Red-DiscordBot/cogs/CogManager/cogs/casino/casino.py", line 465, in memdesigner
    await Membership(ctx, timeout, choice.content.lower()).process()
  File "/home/kstjohn_kstj_us/.local/share/Red-DiscordBot/cogs/CogManager/cogs/casino/casino.py", line 877, in process
    await action()
  File "/home/kstjohn_kstj_us/.local/share/Red-DiscordBot/cogs/CogManager/cogs/casino/casino.py", line 892, in delete
    "{}.").format(utils.fmt_join(memberships)))
  File "/home/kstjohn_kstj_us/.local/share/Red-DiscordBot/cogs/CogManager/cogs/casino/utils.py", line 37, in fmt_join
    return words[0]
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 570, in invoke
    await super().invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1158, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 0

**Comment by aikaterna** [comment]
Resolved in 5c36cbafa4916d4ea465fcf22bb1a5713c9c33a6
