### ISSUE TITLE
Race Cog error

### ISSUE THREAD

**Issue by Majesty01** [Redjumpman/Jumper-Cogs#241]
Traceback (most recent call last):
  File "c:\users\administrator\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\friends\cogs\CogManager\cogs\race\race.py", line 114, in start
    await self._race_teardown(ctx, settings)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\friends\cogs\CogManager\cogs\race\race.py", line 393, in _race_teardown
    await self.bet_payouts(ctx, settings)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\friends\cogs\CogManager\cogs\race\race.py", line 430, in bet_payouts
    await bank.deposit_credits(user, (int(bet * multiplier)))
  File "c:\users\administrator\redenv\lib\site-packages\redbot\core\bank.py", line 388, in deposit_credits
    bal = await get_balance(member)
  File "c:\users\administrator\redenv\lib\site-packages\redbot\core\bank.py", line 220, in get_balance
    acc = await get_account(member)
  File "c:\users\administrator\redenv\lib\site-packages\redbot\core\bank.py", line 621, in get_account
    all_accounts = await _config.all_members(member.guild)
AttributeError: 'User' object has no attribute 'guild'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\administrator\redenv\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\administrator\redenv\lib\site-packages\redbot\core\commands\commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "c:\users\administrator\redenv\lib\site-packages\discord\ext\commands\core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "c:\users\administrator\redenv\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, ctx.kwargs)

**Comment by Merp-Me** [comment]
Got the same error on bank being local. The race was functioning properly though, the bot only said that there was an error after the race had finished as shown in the image.
![image](https://user-images.githubusercontent.com/64408204/109328435-5ba29d80-7851-11eb-8d2f-dc940ba1c19e.png)

**Comment by aikaterna** [comment]
Fixed in f48cc89
