### ISSUE TITLE
Bot stats - tuple index out of range

### ISSUE THREAD

**Issue by Dexthor** [Redjumpman/Jumper-Cogs#28]
Does this error happen because of having too many chips? or is it a bug?

` ERROR red on_command_error 181: Exception in command 'casino stats'
Traceback (most recent call last):
  File "C:\Users\Dex\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "cogs\casino.py", line 501, in _stats_casino
    "{}".format(membership, chip_name, chip_balance))
IndexError: tuple index out of range`

**Comment by Dexthor** [comment]
Its fixed. Was an issue on my end. 
Sorry!
