### ISSUE TITLE
Shop Notification turned on

### ISSUE THREAD

**Issue by Tiago0** [Redjumpman/Jumper-Cogs#73]
Exception in command 'shop redeem'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/cogs/shop.py", line 88, in _redeem_shop
    await self.notify_handler(settings, ctx, itemname, user, confirmation_number)
  File "/cogs/shop.py", line 830, in notify_handler
    await self.bot.send_message(destination, msg)
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "lib/discord/client.py", line 276, in _resolve_destination
    channel = yield from self.start_private_message(destination)
  File "lib/discord/client.py", line 916, in start_private_message
    data = yield from self.http.start_private_message(user.id)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send messages to this user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Cannot send messages to this user

**Comment by Redjumpman** [comment]
This bug is because the user won't allow the bot to send them a DM. The user needs to allow this, since buy_msgs are supposed to be private.
